### ISSUE TITLE
Inverse Kinematics: All models work fine, except for beast which doesn't work at all

### ISSUE THREAD

**Issue by IgorStempen** [dilevin/computer-graphics-kinematics#1]
Hi,

I have completed my inverse kinematics code, and all of my models work perfectly, except for beast. For all models except beast, the bones follow the end-affector positions without any issues. But when I run beast, the bones either do not move at all, or move to ridiculous positions. 

I tried to debug, and it seems like the gradient direction returned by the gradient function does not reduce the energy at all, no matter what value of sigma I multiply the gradient by.

Why is the behavior of my beast model so much different than the behavior of my knight model? It seems like these two models are almost identical, and only differ by a few bones and angle constraints.

Any advice is appreciated.

Thanks.

**Comment by exbibyte** [comment]
It might be parameter tuning for line search, i had to tweek that and how it terminates to get a good enough step delta. Otherwise, maybe missing parameter projections somewhere.

**Comment by IgorStempen** [comment]
But if I just take small steps in my gradient direction, I would eventually end up minimizing the energy. It would just take longer? I could see the issue being my projection but I don't think I could have made a mistake there.

**Comment by clearlycloudy** [comment]
i think the model is nonlinear with respect to the parameters so you might end up with a bad minima if you take too small of a step. That bad minima corresponds to some weird model configuration.

**Comment by exbibyte** [comment]
i think the model configuration is non linear wrt parameters. so step size could affect where in state space the jacobian is evaluated at next iteration. Some bad minima can correspond to some bad model configuration.

**Comment by IgorStempen** [comment]
It ended up being my line search in the end. Thanks for the help!
