### ISSUE TITLE
cannot access keyframes?

### ISSUE THREAD

**Issue by jwmaggiezhou** [dilevin/computer-graphics-kinematics#10]
![image](https://user-images.githubusercontent.com/21364786/55026900-5344e680-4fda-11e9-9065-fa6df4f17f70.png)

Getting segmentation fault because of this issue, not sure what maybe the root cause?

**Comment by itsvismay** [comment]
keyframes might be empty. Try back-tracing (bt) in gdb for more info

**Comment by stefanstancu** [comment]
Not all the keyframes that are passed into the interpolation function have values (i.e. some are null).

If you take a look at main.cpp you'll see that each bone has a list of keyframes, so some might be null if that bone shouldn't be moving (like the root bone).
