### ISSUE TITLE
In Kinematics_Jacobion, why isn't 'A' passed in? Or am I missing something? 

### ISSUE THREAD

**Issue by ACalza** [dilevin/computer-graphics-kinematics#11]
Basically, I don't understand why the angles aren't passed in. I see myself for-looping through the skeleton to get the angles so I can properly call transformed_tips with the small delta in A. 

When we want to finite-difference, we need the Euler angles. Unless I'm missing something in the signature, what's up?

Is it something I'm not getting? Thanks!

**Comment by disconcision** [comment]
The base angles are in the skeleton. You can make new skeletons with angles perturbed by epsilon.

**Comment by ACalza** [comment]
Yeah, but isn't that just a waste/inefficient? Why not pass the Skelton angles from the gradient function? I'm just asking since I'm "re-building" the Euler angles array in the beginning of the function, and see no use for the parameter in the gradient function anymore.

I would change the header file if I could....

My 'new' skeletons should consist of the the Euler angles passed from the gradient + some epsilon. tldr; I don't understand the use of passing the Euler angles in the gradient function if we can't even pass it to the Jacobin function. Seems kind of a waste.

**Comment by vsytch** [comment]
Since you're passing the Jacobian by reference, you can just pass the skeleton angles in the first row of it.

**Comment by ACalza** [comment]
Ah gotchya
