### ISSUE TITLE
latex on A7 website

### ISSUE THREAD

**Issue by wufengta** [dilevin/computer-graphics-kinematics#12]
All the formulas in A7 are showed in raw latex language which I cannot just copy paste into the lastex editor to know what it is saying....I saw someone can read the formulas rather than latex language in browser, can anyone please tell me what I should do to transform latex into math formulas?
e.g: 
 $(\ell,0,0)$ maps to the "rest tip" $\hat{\d} ∈ \R³$: $$ \hat{\d} = \hat{\T} \left(\begin{array}{c}\ell\\0\\0\\1\end{array}\right) = \hat{\Rot}\left(\begin{array}{c}\ell\\0\\0\end{array}\right) + \hat{\t}. $$

$\hat{\T}$ is simply the tail position, $\hat{\s}∈\R^3$: $$ \hat{\s} = \hat{\T} \left(\begin{array}{c}0\\0\\0\\1\end{array}\right) = \hat{\Rot} \left(\begin{array}{c}0\\0\\0\end{array}\right) + \hat{\t} 1 = \hat{\t}. $$

**Comment by wufengta** [comment]
[](url)### ****

**Comment by umarfarooq96** [comment]
Open the .html file
