### ISSUE TITLE
Very confused with projected gradient descent mathematics

### ISSUE THREAD

**Issue by auderian** [dilevin/computer-graphics-kinematics#15]
The step taken in the iterative algorithm is expressed (from the lab manual) as 
`a <- a - σJT(dE(x)/dx)`
I think I understand how to determine J, but I have no idea how to determine dE(x)/dx inside the gradient function in end_effectors_objective_and_gradient.cpp. The furthest I've gotten in my reasoning is using the fundamental theorem of calculus to determine the gradient from a small change in x, but I don't understand how to then divide out that small difference. Are we supposed to do it component-wise?

**Comment by stefanstancu** [comment]
Take the derivative of E(x) wrt to x. E(x) = ||x - **x**||^2. You can just take the derivative like any other function. Your result should be a vector that is b.size()*3 large. If you're still confused  you can google mean square error derivative and there's all sorts of websites that explain how the derivative works in detail.

**Comment by auderian** [comment]
I think I got it, thanks!
