### ISSUE TITLE
spline interpolation near boundary

### ISSUE THREAD

**Issue by exbibyte** [dilevin/computer-graphics-kinematics#2]
For handling boundary segements of a spline where there isn't enough control points near the vicinity, are we assumed to use linear interpolation to take acount of those boundary points? I see jerkiness if I try to omitt or clamp values with cubic spline.

**Comment by JeremySant** [comment]
Can we look at the animation frames as a loop, since they all start and end in the rest position? If so there are no boundaries since we can just loop around the values.

**Comment by itsvismay** [comment]
^ Yeah, I believe Jeremy is correct.

**Comment by csc418-anon** [comment]
I have a follow up question, if our spline is at the start, wouldn't we need to use finite differences to determine the tangent? Or am I really off base here. Not really sure what @JeremySant meant by 'loop over the values.'

**Comment by csc418-anon** [comment]
I'm having issues with the boundary. I'm wrapping around the values as suggested above (so p0 would be the start of the loop again, and P1, and P2 would be the segment where we interpolate), however I'm getting weird jitters. I'm covering the base cases. It works perfectly when I linearly interpolate, but during the edge cases I get this: Any ideas? 

![weird jitters](https://user-images.githubusercontent.com/48340920/54882302-e50ff080-4e2e-11e9-9e68-02d90427ac92.gif)

**Comment by exbibyte** [comment]
I finally had time to work on this again, and yes the animation loop assumption works. You'd just have to extend the given keyframes with a few extra frames near boundary and with the max time offset adjustments.
