### ISSUE TITLE
Why does forward_kinematics need to be recursive?

### ISSUE THREAD

**Issue by RaihanFaruque** [dilevin/computer-graphics-kinematics#21]
Each bone has its parent index, and the parent has  transformation from"canonical bone" to "rest bone"

**Comment by andriyDev** [comment]
It doesn't really need to be recursive, you can use a stack. It's mostly so that you can be certain that the order of the bones won't break anything.

**Comment by MstrPikachu** [comment]
Does this mean there is no guarantee that the parent index is less than the child index?

**Comment by Zhecheng-Wang** [comment]
>Does this mean there is no guarantee that the parent index is less than the child index?

There is no guarantee. It was never a given assumption.
