### ISSUE TITLE
Confusion with paramter of functions in end_effectors_objective_and_gradient

### ISSUE THREAD

**Issue by ilan-segal** [dilevin/computer-graphics-kinematics#28]
The documentation specifies that parameter A is a vector of Euler angles, of size #bones. Since each bone has 3 Euler angles, this means that A does not have enough Euler angles to specify an entire pose. How, then, are we supposed to interpret the values in A?

**Comment by honglin-c** [comment]
Sorry for the mistake in the documentation. A should be a vector of #bones*3 of Euler angles, ordered in the same way as the A in copy_skeleton_at.h.
