### ISSUE TITLE
Forward Kinematics Interpolation looks different than README

### ISSUE THREAD

**Issue by IgorStempen** [dilevin/computer-graphics-kinematics#3]
Hi,

My Forward kinematics for the robot-arm looks smooth but does not seem to match the example shown in the README. I was wondering if this is ok? Or do we need to match the README exactly?

![arm](https://user-images.githubusercontent.com/14172179/54732277-528afb00-4b69-11e9-8c7d-4fe06a31f027.gif)

The arm looks a little choppy in the gif but it looks very smooth on my computer.

**Comment by itsvismay** [comment]
I'm not sure what key-frame data the readme animation is using for the arm. I can check with Gavin or Dave, but I think if the input data is the same, it should match the README.

**Comment by IgorStempen** [comment]
Could my interpolation produce an animation that looks slightly off, even if all the individual key-frames are correct?

**Comment by AllenLXL** [comment]
I think example of README uses linear interpolation...

**Comment by bod11** [comment]
The position of the arm in the readme is an at angle and not the default position, so make sure you match it up. But I got the movement in the readme, or very close to it, with catmull-rom  interpolation. You arm seems to spin a bit while it's moving at the beginning and end of the animation, mine isn't doing that. If that's any help....

**Comment by IgorStempen** [comment]
Did you use standard catmull-rom interpolation or some variant on it (such as centripital catmul rom)?

**Comment by bod11** [comment]
I used standard catmull-rom straight from wikipedia

**Comment by bod11** [comment]
Not sure if it matters if it's slightly off, hopefully the prof lets you know. Yours still looks good so idk :P.

**Comment by buencons** [comment]
I used centripetal catmull-rom and my robot arm looks like this:
![demo](https://user-images.githubusercontent.com/19580484/54894100-66976b00-4e8f-11e9-8cb9-023f3d935193.gif)
Would this be fine?
