### ISSUE TITLE
Jacobian matrix values

### ISSUE THREAD

**Issue by Jiogit** [dilevin/computer-graphics-kinematics#33]
Could a Jacobian matrix have 0 values? Or is that a sign of something wrong

**Comment by rishikant-sharma** [comment]
**Student Response**

I believe the Jacobian matrix shows the rate of change of the end effector positions w.r.t the angles. 

A 0 value in a Jacobian Matrix would imply that changing the corresponding joint angle slightly produces no change in the corresponding end-effector position. 
This is true for joint angles that are not on that path from the end effector to the root bone but seems unlikely for all the angles that are on that path.
