### ISSUE TITLE
why do we need copy_skeleton

### ISSUE THREAD

**Issue by triangleCZH** [dilevin/computer-graphics-kinematics#36]
When I try to use copy_skeleton in end_effactors_obj, I find that the only two functions using a skeleton are kinematics_jacobian and transformed_tips. They all have skeleton as const argument, which will not change the skeleton, so I wonder if it is really necessary to copy the skeleton

**Comment by triangleCZH** [comment]
It is interesting that it starts very slow (need some seconds to react before go to the correct pose) if I directly use the original skeleton in kine_jacobian and transform_tips; I don't have this problem if I make a copy of skeleton and pass it into those functions.
Any ideas on why a direct passing is slower?

**Comment by honglin-c** [comment]
That's interesting! Did you set the skeleton's `xzx` to the Euler angles `A` in `f`  and 
`grad_f` before passing it into `transformed_tips` and `kinematics_jacobian`? The parameter `skeleton` is a constant in `end_effectors_objective_and_gradient` so I don't think you can change its `xzx` without making a copy.

**Comment by triangleCZH** [comment]
Thank you for the suggestion. That makes sense to me. I cannot set xzx with A without copy_skeleton. Then it will be rather interesting that all the functions work without setting A (it is merely a little bit slower at the start)
