### ISSUE TITLE
Forward Kinematics interpolation Catmull issues

### ISSUE THREAD

**Issue by csc418-anon** [dilevin/computer-graphics-kinematics#4]
Having issues with interpolating the points. Right now, I looked over the code through several hours, and I'm still stuck on this. As of now I am confident that I have my matrices set up properly when interpolating, however the tips of the fingers aren't animating, and the animation is all over the place. I've tried everything to debug, even went back to linear interpolation to see what was up, still not looking like anything I need it to be. I'm going to post a video of the time-lapse: 
![shitface](https://user-images.githubusercontent.com/48340920/54859375-bc7ae000-4ce2-11e9-8e68-545a6058b472.gif)
EDIT: It's actually much faster than what the gif shows above.

And this is when a LINEARLY interpolate between the keyframes with the robot arm: 
![shit2](https://user-images.githubusercontent.com/48340920/54859437-91dd5700-4ce3-11e9-9bcf-d5d2cff6c87a.gif)

Also, what do we do in the boundary cases? When we try to interpolate the spline that is between the first two points, what do we do then? Linear interpolation? Either way, I don't know what's wrong with this. Any suggestions would be amazing!

**Comment by csc418-anon** [comment]
Convert degrees to radians....Whoops..................................................................................................

/facepalm

**Comment by AlekseyPanas** [comment]
you saved me!
