### ISSUE TITLE
Which files should I check if the model does not move when dragging the points?

### ISSUE THREAD

**Issue by JoAndNight** [dilevin/computer-graphics-kinematics#48]
https://github.com/dilevin/computer-graphics-kinematics/raw/master/images/knight-dab.gif
As in this gif, when dragging the points, the model is supposed to move.
I was able to do this when I only implemented cpp files for forward kinematics. However, after I implemented all the other files, I couldn't move the model anymore.
I assume that `transformed_tips.cpp`, `euler_angles_to_transform` and `forward_kinematics` are files related to dragging and moving, but is it possible that the bugs in other files may also cause this?

**Comment by Shujie24** [comment]
Hi JoAndNight, do you know which file to check now? I've encountered the same problem.
