### ISSUE TITLE
Line search optimal step rate

### ISSUE THREAD

**Issue by Mincelot** [dilevin/computer-graphics-kinematics#5]
How fast does our end effectors have to move towards the dot? After sometimes of tuning the parameters I don't think the condition that passing the equality is sufficient for the convergence speed shown in the gif.

**Comment by bod11** [comment]
You may have your line search and projection gradient functions slightly off. I was needing to adjust the parameters to get movement in all of the models, but after fixing an issue with my functions I was able to get all of the models to move normally using 10000 as the max step and 1/2 as step difference, exactly what was used in the readme. Also, to get it to look like the readme you need to be on a release build.

**Comment by Mincelot** [comment]
The main problem for me wasn't that the model doesn't move but for model like beast it seems the result from line search produce a bad sigma such that the limbs is shaking around the dot position, not sure why this happens because if my gradient is wrong then it shouldn't work with small sigma.
