### ISSUE TITLE
No bending for inverse kinematics?

### ISSUE THREAD

**Issue by nicholas3d2** [dilevin/computer-graphics-kinematics#52]
Hello,

When dragging the end points around, the bones will only twist to try and match the end position and won't bend at all. This is only an issue for IK since I'm able to match the solution animations when running FK...

Can I get any hints as to where the issue might be?

Thanks!

**Comment by Zhecheng-Wang** [comment]
By only twist, do you mean the joint always stays static but only rotates along itself?

If so, that sounds like an indexing issue during optimization.

**Comment by nicholas3d2** [comment]
Hi, yes the lamp looked like this:
<img width="926" alt="Screenshot 2023-11-14 at 4 40 36 PM" src="https://github.com/dilevin/computer-graphics-kinematics/assets/61950668/4e72f711-7f9e-4836-9870-7b832e688810">

It was an issue with proj_z, thanks!
