### ISSUE TITLE
What "max_step" in "line_search()" means?

### ISSUE THREAD

**Issue by wangshangsam** [dilevin/computer-graphics-kinematics#6]
Does "max_step" in "line_search()" mean the "sigma" (learning rate?) or "sigma * the norm of the gradient" (the **actual distance** in the direction of the gradient)?

**Comment by bod11** [comment]
I believe it means sigma, since max step * dz should give you the step. It's the starting sigma since you will iterate to a smaller sigma.

**Comment by wangshangsam** [comment]
> I believe it means sigma, since max step * dz should give you the step. It's the starting sigma since you will iterate to a smaller sigma.

That's what I thought at the beginning too, but when I saw "maximum step to take in dir" in the header file, technically speaking, it means "max_step * the unit vector in the (negative) gradient direction". As in, "max_step" is the maximum length of the updating vector.

**Comment by bod11** [comment]
making it equal to sigma and inputting 10000 in the projection gradient when calling line search seems to have worked for me. Not sure if I am doing it wrong but it works out either way.
