### ISSUE TITLE
Issues with spline interpolation (stuck) 

### ISSUE THREAD

**Issue by csc418-anon** [dilevin/computer-graphics-kinematics#9]
> I'm having issues with the boundary. I'm wrapping around the values as suggested above (so p0 would be the start of the loop again, and P1, and P2 would be the segment where we interpolate), however I'm getting weird jitters. I'm covering the base cases. It works perfectly when I linearly interpolate, but during the edge cases I get this: Any ideas?
> 
> ![weird jitters](https://user-images.githubusercontent.com/48340920/54882302-e50ff080-4e2e-11e9-9e68-02d90427ac92.gif)

This is a quote from a recently close issue. I still don't know what's up with it. Since the 'gaps' occur mid-way through the 6 second animation? right now I'm interpolating between each point with the basis cardinal matrix (but the assumption is that each point is separated evenly).

**Also note, due to the high quality gif, it's going to look extra gittery, so I don't think the gif does it justice. Basically mid-way through the animation, the arm jumps from one side to the other.**

**Comment by itsvismay** [comment]
Try a linear interpolation first, make sure that works. Then check the new interpolation method. If there's something wrong with the animation, then its likely a bug in the new interpolation method.

**Comment by csc418-anon** [comment]
Thanks for the reply! Linear interpolation DOES work 100%. However the way I'm currently interpolating is using a basis matrix with the respected points. 

So my implementation -assumes- each point is spaced out evenly. In linear interpolation that was not the case. But from the notes that's what Catmull interpolation assumes.

**Comment by csc418-anon** [comment]
Yeah I made the assumption that each point is spaced evenly. I updated the algorithm so it takes into account that the points are not spread out evenly in terms of time.
